# Generated by Django 3.2.5 on 2021-07-29 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0005_alter_category_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
